name: test

on:
  push:
    branches:
      - 'main'
      - 'feature/**'
  pull_request:
    branches:
      - 'main'

env:
  PNPM_VERSION: '9.15.2'

jobs:
  test:
    strategy:
      matrix:
        platform:
          - 'ubuntu-latest'
          # - 'macos-latest'
          # - 'windows-latest'
        node-version:
          - '22.12.0'
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Set up pnpm
        uses: pnpm/action-setup@v4
        with:
          version: ${{ env.PNPM_VERSION }}
      - name: Set up Node.js
        uses: actions/setup-node@v5
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
      - name: Run CI tests
        shell: bash
        run: |
          make ci-test
